import { DefaultTheme } from "styled-components";

export const theme: DefaultTheme = {
  colors: {
    light: "#FFFFFF",
    gray: "#FFFFFF4D",
    thin_gray: "#A3A3A3",
    dark_blue: "#0E192D",
    dark_color: "#000000",
    blur_color: "#0000004d",
    hero_pink_color: "#d8587e",
    price_link_color: "#079dab",
    price_title_color: "#5e6775",
    header_menu_color: "#57606d",
    light_green_color: "#49bbbd",
    video__circle_red: "#ff6a6a",
    vide_blur_color: "#ffffff1a",
    group_course_color: "#f3f3f3",
    footer_input_color: "#d8d8d8",
    chevron_icon_color: "#9ca3af",
    directive_link_color: "#285fae",
    directive_span_color: "#118a50",
    video__element_color: "#5b61eb",
    hero_bottom_box_color: "#2c3e50",
    hero_activity_color: "#ffffffcc",
    language_option_color: "#e2e8f0",
    hero_chart_pink_color: "#f3627c",
    directive_title_color: "#2f327d",
    header_drop_down_color: "#2d3748",
    header_container_color: "#58626f",
    swiper_group_link_color: "#324361",
    swiper_group_text_color: "#4d4d4d",
    swiper_slide_item_color: "#f6f7f9",
    successfully_four_color: "#aa5e2b",
    successfully_first_color: "#ea8d32",
    successfully_third_color: "#f25471",
    successfully_second_color: "#a83adc",
    hero_chart_shadow_color: "#d24d6542",
    footer_content_text_color: "#999999",
    directive_item_text_color: "#696984",
    header_btn_shadow_color: "#00000008",
    footer_security_text_color: "#b2b3cf",
    footer_result_link_color: "#00000040",
    testimonials_another_color: "#f67766",
    directive_second_link_color: "#112748",
    language_option_hover_color: "#4a5568",
    group_course_swiper_color: "#2f327d1a",
    testimonials_content_color: "#292c7c1a",
    question_box_item_text_color: "#7b7b7b",
    hero_content_span_first_color: "#d4bf6e",
    premium_course_section_color: "#49bbbd33",
    hero_content_span_second_color: "#806233",
    footer_input_placeholder_color: "#494949",
    group_course_swiper_title_color: "#252641",
    testimonials_navigation_color: "#292c7c26",
    premium_course_section_text_color: "#ca9219",
    premium_course_content_text_color: "#767acc",
    flag_circle_box_shadow: "rgba(0, 0, 0, 0.2)",
    testimonials_box_content_text_color: "#5f5f7e",
    road_section_color: "rgba(157, 204, 255, 0.2)",
    swiper_navigation_container_color: "#282b6f1a",
    footer_container_color: "rgba(37, 38, 65, 0.8)",
    directive_section_color: "rgba(5, 16, 59, 0.8)",
    testimonials_navigation_hover_color: "#292c7c40",
    testimonials_box_content_border_color: "#bdbdd1",
    header_container_box_shadow: "rgba(0, 0, 0, 0.1)",
    swiper_slide_background_color: "rgba(0, 0, 0, 0.05)",
  },
  font: {
    poppins: "'Poppins', sans-serif",
  },
};
